language: php

before_install:
  - phpenv config-rm xdebug.ini

php:
  - 5.5
  - 5.6
  - 7

script:
  - ./vendor/bin/phpunit tests
  - ./vendor/bin/php-cs-fixer fix . --level=psr2 --verbose --dry-run

cache:
  directories:
  - $HOME/.composer/cache/repo/
  - $TRAVIS_BUILD_DIR/vendor/

branches:
  only:
    - master
